### PR TITLE
Add up, down, and update commands to cmd.sh

### PR DESCRIPTION
**Pull request by mediocregopher**
Each command has been added for a different reason:

* `up`: docker-compose has some wonky behavior regarding how it deals
with configuration. I would like to move towards having a single unified
configuration file (or set of files) where the behavior of the node and
its services can be modified. In order to do that, due to
docker-compose's wonkiness, we're going to need a wrapper command. Might
as well make it `up`.

* `down`: To be symmetric with `up`.

* `update`: We don't have it in place now, but eventually there are
going to be backwards incompatible changes which need to be made which
will require more than a `git pull` (e.g. moving a user's configuration
files from A to B). Having an `update` command lets us have the ability
to automate these changes in the future.

This commit also changes the docs accordingly.

### CODE REVIEW

**Review by cap10morgan — APPROVED** [review]
I 100% believe you that this will be necessary, but I think I'd prefer to review the changes in the context of what they'll enable, at least in a very minimal first step kind of way.

But if that's not how you'd prefer to roll them out, that's OK too. I'll leave that decision up to you.

**Comment by mediocregopher** [comment]
So tbh I had another change lined up after this one which _did_ use at least the new `up` command, but I was waiting to see what you thought of this one. I went ahead and pushed that change to this MR though. Essentially, adding a basic configuration

**Comment by cap10morgan** [comment]
I want to understand the docker-compose wonkiness a little more. For instance, couldn't you just use a `.env` file with defaults or even specify one with the `env_file:` param in `docker-compose.yml`? And then just have users edit those if they need something different?

I'm not opposed to a wrapper, just want to make sure I understand what it's getting us and/or helping us avoid.

**Comment by mediocregopher** [comment]
I guess what makes it more difficult than just having an `.env` file is that I wanted to have a file which isn't being tracked by git which can be edited by users, but then also have a file which _is_ in git which could be fallen back on to fetch the default configuration values. That way we could ship new versions with new config parameters without users needing to worry about having their own config accidentally overwritten or conflicting.

The wonkiness in docker is that environment variables essentially exist in two different universes:

* `docker-compose.yml` templated variables can be set via the user's shell environment or `--env-file` (which defaults to `.env`). The `env_file` directive within `docker-compose.yml` has no effect on the template variables.

* Within a container the environment variables can only be set via the `environment` or `env_file` directives in `docker-compose.yml`. The `--env-file` command-line argument (and `.env`) have no affect on container environments.

Since the only way to affect container environment (which we're not currently doing, but we probably will) is with `env_file`, it seemed like the best way to accomplish this was to have a default set of environment variables, and then allow the user to create a file with an overriding set.

**Comment by cap10morgan** [comment]
OK, that all makes sense. Kind of annoying on docker-compose's part that the env stuff is so complicated. I'm 👍 on merging this.

**Comment by mediocregopher** [comment]
> Kind of annoying on docker-compose's part that the env stuff is so complicated

Truly.

Thanks! :pray:

**Pull request merged**
